services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=MyCassandraCluster
      - CASSANDRA_DC=DC1
      - CASSANDRA_RACK=Rack1
      - CASSANDRA_LISTENER_INTERFACES=eth0
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    ports:
      - "9042:9042"
      - "7000:7000"
    healthcheck:
      test: [ "CMD-SHELL", "cqlsh -e 'describe keyspaces' || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - my-network


  akkamelo:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: akkamelo
    depends_on:
      cassandra:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 256M
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - JAVA_OPTS=-Xmx512m
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/docker-compose"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
